# Generated by Django 5.2.7 on 2025-10-02 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='students/'),
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('father_name', models.CharField(max_length=30)),
                ('mother_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('registration', models.IntegerField(unique=True)),
                ('religion', models.CharField(max_length=20)),
                ('birthdate', models.DateField()),
                ('marital_status', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='teachers/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
