# Generated by Django 5.2.7 on 2025-10-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarian',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='librarians/'),
        ),
    ]
